---
mgmt_ip: 127.0.0.1
ssh_port: 3222
http_port: 3280
https_port: 3243
netconf_port: 3230
username: vagrant
password: vagrant
interfaces:
    - name: Loopback11
      desc: Sample Network Route Injection
      ip_address: 172.22.1.1
      prefix: 24
    - name: Loopback12
      desc: Sample Network Route Injection
      ip_address: 172.22.2.1
      prefix: 24
    - name: Loopback13
      desc: Sample Network Route Injection
      ip_address: 172.22.3.1
      prefix: 24
    - name: Loopback14
      desc: Sample Network Route Injection
      ip_address: 172.22.4.1
      prefix: 24
    - name: Ethernet1/1
      desc: Link to other switch
      ip_address: 172.20.0.2
      prefix: 24
mac_addresses:
    - interface: Ethernet1/1
      address: 0000.0000.2001
    - interface: Ethernet1/2
      address: 0000.0000.2002
