##############################################################
# Learning Series: Network Programmability Basics
# Module: NetDevOps
# Lesson: Ansible Part 2: Using Ansible for Network Configuration
# Author: Hank Preston <hapresto@cisco.com>
# 
# example1.yaml
# Illustrate the following concepts:
# - Basic Playbook Structure for NX-OS Modules
##############################################################
---
- name: Provision NX-OS Devices
  hosts: default
  connection: local
  
  tasks: 
    - name: Pause to complete boot
      pause: 
        seconds: 5
        
    - name: Enable NX-API
      nxos_feature:
        host: "{{ mgmt_ip }}"
        port: "{{ ssh_port }}"
        username: "{{ username }}" 
        password: "{{ password }}"
        transport: cli 
        feature: nxapi
        state: enabled 
        
    - name: Create Loopback Interface
      with_items: "{{ interfaces }}"
      nxos_interface: 
        host: "{{ mgmt_ip }}"
        port: "{{ ssh_port }}"
        username: "{{ username }}" 
        password: "{{ password }}"
        transport: cli 
        interface: "{{ item.name }}"
        mode: layer3
        description: "{{ item.desc }}"
        admin_state: up
    - name: Configure IPv4 Address on Interface
      with_items: "{{ interfaces }}"
      nxos_ip_interface:
        host: "{{ mgmt_ip }}"
        port: "{{ ssh_port }}"
        username: "{{ username }}" 
        password: "{{ password }}"
        transport: cli 
        interface: "{{ item.name }}"
        version: v4
        addr: "{{ item.ip_address }}"
        mask: "{{ item.prefix }}"  
